const channels = ["search_ads", "linkedin", "content_marketing", "referral_program"];
const plans = ["A", "B", "C"];
let state = null;

const $ = (id) => document.getElementById(id);

const helpText = {
  day: "Current simulated day. The GUI advances the company one week at a time.",
  cash: "Money available to the company. Ending cash is the main score in this no-LLM run.",
  mrr: "Monthly recurring revenue from active subscriptions, before future churn or expansion.",
  subscribers: "Total active paying subscribers or seats currently using the product.",
  individual: "Active individual/self-serve customers, as opposed to enterprise seats.",
  enterpriseSeats: "Seats under active enterprise subscriptions. One enterprise customer can represent many seats.",
  openIssues: "Unresolved customer problems. More unresolved issues usually indicate service or support strain.",
  capacity: "Infrastructure scale available to serve usage. Higher tiers cost more but can reduce overload risk.",
  price: "Monthly list price for this plan. Higher price raises revenue per customer but can reduce conversion or satisfaction.",
  modelTier: "Quality/cost class of the AI model served on this plan. Higher tiers are generally better and more expensive to operate.",
  quota: "Included daily usage allowance per customer on this plan. Higher quotas can improve value but may increase compute load.",
  operationsSpend: "Daily budget for reliability, support, and operational execution. It is the boring but useful glue budget.",
  developmentSpend: "Daily product engineering budget. It improves the product over time rather than buying immediate demand.",
  capacityTier: "Purchased infrastructure tier. Think of this as the size of your serving setup, not the model quality.",
  adsStrength: "How aggressively ads are shown inside the product. It can create ad revenue, but users may dislike too much of it.",
  promo: "Discount for existing subscribers. It can reduce churn pressure but lowers revenue collected.",
  leadPromo: "Discount shown to new leads for their first billing period. It can improve conversion but lowers first-period revenue.",
  adMatrix: "Paid acquisition budget by channel and segment. This changes where new leads are likely to come from.",
  targetedDevelopment: "Product-development budget aimed at a specific customer group rather than the whole product.",
  targetedOperations: "Operations/support budget aimed at a specific customer group rather than everyone equally.",
  groupId: "Customer segment identifier, such as S1 for an individual segment or E1 for an enterprise segment.",
  targetInfoLevel: "How detailed you want market research to become. Higher levels cost more and take longer.",
  researchMarket: "Spend money to look for an additional customer segment that is not visible yet.",
  researchGroup: "Spend money to improve what you know about a known segment. Results arrive after simulated time passes.",
  rndTier: "R&D project class to start. Higher tiers are usually larger bets, not a guaranteed better immediate move.",
  customerId: "Internal customer identifier used for enterprise negotiations.",
  dealPlan: "Plan you are offering to the enterprise customer.",
  dealPrice: "Monthly price per enterprise seat in the offer.",
  rejectDeal: "Close the active enterprise thread without making a deal.",
  rationale: "Short explanation of your weekly decisions. In this GUI it is recorded for traceability.",
  cashForecasts: "Your own cash predictions for future horizons. They are useful for calibration, not direct control.",
  forecastPoint: "Your best estimate for cash at that future horizon.",
  forecastLower: "Lower bound of your expected cash range.",
  forecastUpper: "Upper bound of your expected cash range.",
  dashboardText: "Text version of the weekly report generated by the simulator.",
  usage: "Total product usage in the latest measured period.",
  p95Latency: "A high-percentile latency measure. It reflects what slower-but-not-worst-case users experience.",
  errorRate: "Share of requests that failed in the latest service measurement.",
  downtime: "Minutes where the service was unavailable or severely impaired.",
  capacityUnits: "Serving capacity available at the current capacity tier.",
  capacityTierMetric: "Current infrastructure tier used by the service.",
  qualityGroup: "Customer segment whose experienced product quality is shown.",
  qualityPlan: "Delivered product quality for this plan and segment. Treat it as a relative product-fit indicator.",
  groupBonus: "Extra quality improvement focused on this customer group.",
  segmentInfo: "How detailed your market knowledge is for this segment.",
  segmentType: "Whether the segment is known from the start or discovered later.",
  discoveredDay: "Simulation day when this segment became visible.",
  activeSubs: "Current active subscribers in this segment.",
  rndStatus: "Whether this R&D project is still running or already completed.",
  rndStarted: "Simulation day when the R&D project was started.",
  rndExpected: "Expected simulation day when the project should complete.",
  rndBoost: "Quality improvement already applied by completed R&D.",
  threadType: "Reason for the enterprise conversation, such as a new lead or renewal.",
  lastSender: "Who sent the most recent message in the enterprise thread.",
  email: "Contact address shown for the enterprise customer.",
};

function money(v) {
  if (v === null || v === undefined || Number.isNaN(Number(v))) return "-";
  return `$${Number(v).toLocaleString(undefined, { maximumFractionDigits: 0 })}`;
}

function num(v) {
  if (v === null || v === undefined || Number.isNaN(Number(v))) return "-";
  return Number(v).toLocaleString(undefined, { maximumFractionDigits: 0 });
}

function pct(v) {
  if (v === null || v === undefined || Number.isNaN(Number(v))) return "-";
  return `${(Number(v) * 100).toFixed(2)}%`;
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function tip(key) {
  const text = helpText[key];
  if (!text) return "";
  const safe = escapeHtml(text);
  return `<span class="info-tip" tabindex="0" role="tooltip" title="${safe}" aria-label="${safe}" data-tip="${safe}">?</span>`;
}

function labelText(text, key) {
  return `<span class="label-text">${escapeHtml(text)}${tip(key)}</span>`;
}

function controlLabel(text, key, inputHtml) {
  return `<label>${labelText(text, key)}${inputHtml}</label>`;
}

async function api(path, options = {}) {
  const res = await fetch(path, {
    headers: { "Content-Type": "application/json" },
    ...options,
  });
  const data = await res.json();
  if (!res.ok || data.success === false) {
    throw new Error(data.detail || data.message || data.error || "Request failed");
  }
  return data;
}

function toast(message) {
  const el = $("toast");
  el.textContent = message;
  el.classList.add("show");
  setTimeout(() => el.classList.remove("show"), 3600);
}

function setBusy(on) {
  $("busy").classList.toggle("hidden", !on);
}

async function loadState() {
  state = await api("/api/state");
  render();
}

function render() {
  renderStatus();
  renderBriefing();
  renderControls();
  renderMatrices();
  renderTables();
  $("dashboardText").textContent = state.dashboard || "";
  $("subtitle").textContent = `Week ${state.meta.week}, Day ${state.meta.day} of ${state.meta.total_days} Â· LLM disabled Â· social media disabled`;
}

function renderBriefing() {
  const briefing = state.briefing || {};
  $("briefing").innerHTML = `
    <div>
      <h3>${briefing.title || "CEO Briefing"}</h3>
      <p>${briefing.summary || ""}</p>
      <p class="note">${briefing.no_llm_note || ""}</p>
    </div>
    <div>
      <h3>Weekly Workflow</h3>
      <ol>${(briefing.weekly_workflow || []).map((item) => `<li>${item}</li>`).join("")}</ol>
    </div>
    <div>
      <h3>Responsibilities</h3>
      <ul>${(briefing.responsibilities || []).map((item) => `<li>${item}</li>`).join("")}</ul>
    </div>
  `;
}

function renderStatus() {
  const items = [
    ["Day", `${state.meta.day} / ${state.meta.total_days}`, "day"],
    ["Cash", money(state.kpis.cash), "cash"],
    ["MRR", money(state.kpis.mrr), "mrr"],
    ["Subscribers", num(state.kpis.active_subscribers), "subscribers"],
    ["Individual", num(state.kpis.individual_subscribers), "individual"],
    ["Enterprise Seats", num(state.kpis.enterprise_seats), "enterpriseSeats"],
    ["Open Issues", num(state.kpis.open_issues), "openIssues"],
    ["Capacity", `Tier ${state.config.capacity_tier ?? 0}`, "capacity"],
  ];
  $("status").innerHTML = items.map(([label, value, key]) => `
    <div class="stat"><div class="label">${labelText(label, key)}</div><div class="value">${value}</div></div>
  `).join("");
}

function renderControls() {
  $("planControls").innerHTML = plans.map((p) => `
    <div class="plan">
      <h4>Plan ${p}</h4>
      ${controlLabel("Price $/mo", "price", `<input id="price${p}" type="number" min="1" step="1" value="${state.config[`price_${p}`] ?? 0}" />`)}
      ${controlLabel("Model Tier", "modelTier", `<input id="tier${p}" type="number" min="1" max="5" step="1" value="${state.config[`tier_${p}`] ?? 1}" />`)}
      ${controlLabel("Quota units/day", "quota", `<input id="quota${p}" type="number" min="0" step="1000" value="${state.config[`quota_${p}`] ?? 0}" />`)}
    </div>
  `).join("");
  $("opsSpend").value = state.config.spend_operations ?? 0;
  $("devSpend").value = state.config.spend_development ?? 0;
  $("capacityTier").value = state.config.capacity_tier ?? 0;
  $("adsStrength").value = state.ads_strength?.global ?? 0;
  $("promoGlobal").value = state.promotion?.global ?? 0;
  $("leadPromoGlobal").value = state.lead_promotion?.global ?? 0;
  renderForecastDefaults();
}

function knownGroups() {
  return state.segments.map((s) => s.group_id).slice(0, 6);
}

function renderMatrices() {
  const groups = knownGroups();
  const ad = state.ad_spend || {};
  $("adMatrix").innerHTML = [
    `<div class="matrix-row head"><div>${labelText("Channel", "adMatrix")}</div>${groups.map((g) => `<div>${labelText(g, "groupId")}</div>`).join("")}</div>`,
    ...channels.map((ch) => `
      <div class="matrix-row">
        <div class="head">${labelText(ch, "adMatrix")}</div>
        ${groups.map((g) => `<input id="ad_${ch}_${g}" type="number" min="0" step="50" value="${(ad[ch] || {})[g] || 0}" />`).join("")}
      </div>
    `)
  ].join("");

  const dev = state.targeted_dev || {};
  $("targetedDev").innerHTML = [
    `<div class="matrix-row head"><div>${labelText("Spend", "targetedDevelopment")}</div>${groups.map((g) => `<div>${labelText(g, "groupId")}</div>`).join("")}</div>`,
    `<div class="matrix-row"><div class="head">${labelText("$/day", "targetedDevelopment")}</div>${groups.map((g) => `<input id="dev_${g}" type="number" min="0" step="100" value="${dev[g] || 0}" />`).join("")}</div>`
  ].join("");

  const ops = state.targeted_ops || {};
  const opsByGroup = ops.by_group || ops;
  $("targetedOps").innerHTML = [
    `<div class="matrix-row head"><div>${labelText("Spend", "targetedOperations")}</div>${groups.map((g) => `<div>${labelText(g, "groupId")}</div>`).join("")}</div>`,
    `<div class="matrix-row"><div class="head">${labelText("$/day", "targetedOperations")}</div>${groups.map((g) => `<input id="ops_${g}" type="number" min="0" step="100" value="${opsByGroup[g] || 0}" />`).join("")}</div>`
  ].join("");
}

function table(el, columns, rows) {
  $(el).innerHTML = `
    <thead><tr>${columns.map((c) => `<th>${labelText(c.label, c.help)}</th>`).join("")}</tr></thead>
    <tbody>${rows.map((r) => `<tr>${columns.map((c) => `<td>${c.format ? c.format(r[c.key], r) : (r[c.key] ?? "")}</td>`).join("")}</tr>`).join("")}</tbody>
  `;
}

function renderTables() {
  const svc = state.service || {};
  $("serviceMetrics").innerHTML = [
    ["Usage", num(svc.total_usage_units), "usage"],
    ["P95 latency", svc.p95_ms ? `${Number(svc.p95_ms).toFixed(0)} ms` : "-", "p95Latency"],
    ["Error rate", pct(svc.error_rate), "errorRate"],
    ["Downtime", `${svc.downtime_minutes || 0} min`, "downtime"],
    ["Capacity units", num(svc.capacity_units), "capacityUnits"],
    ["Capacity tier", svc.capacity_tier ?? "-", "capacityTierMetric"],
  ].map(([label, value, key]) => `<div class="metric"><span>${labelText(label, key)}</span>${value}</div>`).join("");

  $("ledger").innerHTML = (state.ledger || []).map((r) =>
    `<div class="metric"><span>${labelText(r.category, "cash")}</span>${money(r.amount)}</div>`
  ).join("") || `<div class="metric"><span>${labelText("No ledger rows yet", "cash")}</span>-</div>`;

  table("qualityTable", [
    { key: "group_id", label: "Group", help: "qualityGroup" },
    { key: "A", label: "Plan A", help: "qualityPlan", format: (v) => Number(v).toFixed(4) },
    { key: "B", label: "Plan B", help: "qualityPlan", format: (v) => Number(v).toFixed(4) },
    { key: "C", label: "Plan C", help: "qualityPlan", format: (v) => Number(v).toFixed(4) },
    { key: "group_bonus", label: "Group Bonus", help: "groupBonus", format: (v) => Number(v).toFixed(4) },
  ], state.quality || []);

  table("segmentsTable", [
    { key: "group_id", label: "Group", help: "groupId" },
    { key: "info_level", label: "Info", help: "segmentInfo" },
    { key: "is_discoverable", label: "Type", help: "segmentType", format: (v) => v ? "discovered" : "initial" },
    { key: "discovered_day", label: "Discovered", help: "discoveredDay" },
    { key: "active_subscribers", label: "Active Subs", help: "activeSubs", format: num },
  ], state.segments || []);

  table("rndTable", [
    { key: "tier", label: "Tier", help: "rndTier" },
    { key: "status", label: "Status", help: "rndStatus" },
    { key: "started_day", label: "Started", help: "rndStarted" },
    { key: "expected_completion_day", label: "Expected", help: "rndExpected" },
    { key: "quality_boost_applied", label: "Boost", help: "rndBoost", format: (v) => Number(v || 0).toFixed(4) },
  ], state.research_projects || []);

  table("enterpriseTable", [
    { key: "customer_id", label: "Customer", help: "customerId" },
    { key: "group_id", label: "Group", help: "groupId" },
    { key: "seats", label: "Seats", help: "enterpriseSeats", format: num },
    { key: "thread_type", label: "Type", help: "threadType" },
    { key: "day", label: "Day", help: "day" },
    { key: "sender", label: "Last Sender", help: "lastSender" },
    { key: "email", label: "Email", help: "email" },
  ], state.enterprise_threads || []);
}

function readJsonConfig(key) {
  const value = state.config[key];
  if (!value) return {};
  if (typeof value === "object") return value;
  try { return JSON.parse(value); } catch { return {}; }
}

function renderForecastDefaults() {
  const cash = Number(state.kpis.cash || 0);
  const defs = [
    ["cash_1wk", "+7d", 0.9, 1.1],
    ["cash_4wk", "+28d", 0.75, 1.25],
    ["cash_12wk", "+84d", 0.5, 1.5],
    ["cash_26wk", "+182d", 0.25, 2],
  ];
  $("forecastGrid").innerHTML = defs.map(([key, label, low, high]) => `
    <div class="forecast-card">
      <h3>${labelText(label, "cashForecasts")}</h3>
      ${controlLabel("Point", "forecastPoint", `<input id="${key}_point" type="number" value="${Math.round(cash)}" />`)}
      ${controlLabel("Lower", "forecastLower", `<input id="${key}_lower" type="number" value="${Math.round(cash * low)}" />`)}
      ${controlLabel("Upper", "forecastUpper", `<input id="${key}_upper" type="number" value="${Math.round(cash * high)}" />`)}
    </div>
  `).join("");
}

async function callTool(name, args, { reload = true } = {}) {
  const result = await api(`/api/tool/${name}`, {
    method: "POST",
    body: JSON.stringify({ args }),
  });
  toast(result.message || `${name} applied`);
  if (reload) await loadState();
  return result;
}

function valuesForPlans(prefix) {
  return Object.fromEntries(plans.map((p) => [p, Number($(`${prefix}${p}`).value)]));
}

async function applyCore() {
  const updates = {
    prices: valuesForPlans("price"),
    tiers: valuesForPlans("tier"),
    quotas: valuesForPlans("quota"),
    spend: {
      operations: Number($("opsSpend").value),
      development: Number($("devSpend").value),
    },
    capacity: { tier: Number($("capacityTier").value) },
    adsStrength: { global_strength: Number($("adsStrength").value) },
    promotion: { global_promotion: Number($("promoGlobal").value) },
    leadPromotion: { global_promotion: Number($("leadPromoGlobal").value) },
  };

  await callTool("set_prices", updates.prices, { reload: false });
  await callTool("set_model_tiers", updates.tiers, { reload: false });
  await callTool("set_usage_quotas", updates.quotas, { reload: false });
  await callTool("set_daily_spend", updates.spend, { reload: false });
  await callTool("set_capacity_tier", updates.capacity, { reload: false });
  await callTool("set_ads_strength", updates.adsStrength, { reload: false });
  await callTool("set_promotion", updates.promotion, { reload: false });
  await callTool("set_lead_promotion", updates.leadPromotion, { reload: false });
  await loadState();
  toast("Core settings applied");
}

async function applyAds() {
  const groups = knownGroups();
  const targeted_spend = {};
  for (const ch of channels) {
    const row = {};
    for (const g of groups) {
      const v = Number($(`ad_${ch}_${g}`).value || 0);
      if (v > 0) row[g] = v;
    }
    if (Object.keys(row).length) targeted_spend[ch] = row;
  }
  await callTool("set_targeted_ad_spend", { targeted_spend });
}

async function applyTargetedDev() {
  const targeted_spend = {};
  for (const g of knownGroups()) {
    const v = Number($(`dev_${g}`).value || 0);
    if (v > 0) targeted_spend[g] = v;
  }
  await callTool("set_targeted_dev_spend", { targeted_spend });
}

async function applyTargetedOps() {
  const by_group = {};
  for (const g of knownGroups()) {
    const v = Number($(`ops_${g}`).value || 0);
    if (v > 0) by_group[g] = v;
  }
  await callTool("set_targeted_ops_spend", { by_group });
}

function forecasts() {
  const keys = ["cash_1wk", "cash_4wk", "cash_12wk", "cash_26wk"];
  return Object.fromEntries(keys.map((k) => [k, {
    point: Number($(`${k}_point`).value),
    lower: Number($(`${k}_lower`).value),
    upper: Number($(`${k}_upper`).value),
  }]));
}

function setupEvents() {
  document.querySelectorAll(".tab").forEach((btn) => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".tab").forEach((b) => b.classList.remove("active"));
      document.querySelectorAll(".tab-panel").forEach((p) => p.classList.remove("active"));
      btn.classList.add("active");
      $(btn.dataset.tab).classList.add("active");
    });
  });
  $("refreshBtn").addEventListener("click", loadState);
  $("applyCoreBtn").addEventListener("click", () => wrap(applyCore));
  $("applyAdsBtn").addEventListener("click", () => wrap(applyAds));
  $("applyDevBtn").addEventListener("click", () => wrap(applyTargetedDev));
  $("applyOpsBtn").addEventListener("click", () => wrap(applyTargetedOps));
  $("researchMarketBtn").addEventListener("click", () => wrap(() => callTool("research_market", {})));
  $("researchGroupBtn").addEventListener("click", () => wrap(() => callTool("research_group", {
    group_id: $("researchGroupId").value.trim(),
    target_level: Number($("researchLevel").value),
  })));
  $("startRndBtn").addEventListener("click", () => wrap(() => callTool("start_research_project", {
    tier: Number($("rndTier").value),
  })));
  $("sendDealBtn").addEventListener("click", () => wrap(() => callTool("send_enterprise_deal", {
    deals: [[Number($("dealCustomerId").value), [[$("dealPlan").value, Number($("dealPrice").value)]]]],
  })));
  $("rejectDealBtn").addEventListener("click", () => wrap(() => callTool("reject_enterprise_deal", {
    deals: [{ customer_id: Number($("dealCustomerId").value) }],
  })));
  $("advanceBtn").addEventListener("click", () => wrap(async () => {
    setBusy(true);
    try {
      const data = await api("/api/advance-week", {
        method: "POST",
        body: JSON.stringify({ rationale: $("rationale").value, predictions: forecasts() }),
      });
      state = data.state;
      render();
      toast("Week simulated");
    } finally {
      setBusy(false);
    }
  }));
  $("resetBtn").addEventListener("click", () => wrap(async () => {
    if (!confirm("Reset the current game and start from day 0?")) return;
    state = await api("/api/reset", {
      method: "POST",
      body: JSON.stringify({ seed: 42, days: 500, initial_cash: 1000000 }),
    });
    render();
    toast("Game reset");
  }));
}

async function wrap(fn) {
  try {
    await fn();
  } catch (err) {
    toast(err.message || String(err));
  }
}

setupEvents();
loadState().catch((err) => toast(err.message || String(err)));

globalThis.__ceoBenchApp = {
  applyCore,
  applyAds,
  applyTargetedDev,
  applyTargetedOps,
  callTool,
  loadState,
  render,
  forecasts,
};
